apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: db
  clusterIP: None
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps: db
    spec:
      containers:
      - name: db
        image: mysql:8.0.19
        imagePullPolicy: Always
        ports:
        - containerPorts: 3306
        args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_DATABASE
          value: ctodo
        - name: MYSQL_ROOT_PASSWORD
          value: example
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual # refer to k8s provider ~change this~
  capacity: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual # refer to k8s provider ~change this~
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
