apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: mjwrazor/docker-js-stack-api:v0.1.0
        name: api-container
        imagePullPolicy: IfNotPresent
        resources: {}
        stdin: true
        tty: true
        workingDir: /app
        ports:
        - containerPort: 8080
        args:
        - npm
        - run
        - start
        env:
        - name: MYSQL_DB
          value: ctodo
        - name: MYSQL_HOST
          value: db
        - name: MYSQL_PASSWORD
          value: example
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: test
        - name: PORT
          value: "8080"
      restartPolicy: Always
      volumes: null
      serviceAccountName: ""
status: {}