apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mysql:8.0.19
        name: db-container
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_DATABASE
          value: ctodo
        - name: MYSQL_ROOT_PASSWORD
          value: example
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim