apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
    app.kubernetes.io/name: volume
    app.kubernetes.io/instance: volume-1
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: backend
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes/hostname
          operator: In
          values:
          - node-selector-db
  storageClassName: manual # refer to k8s provider ~change this~
  capacity: 
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"