apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual # refer to k8s provider ~change this~
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi